"""add knowledge schema, documents and chunks with pgvector

Revision ID: 02913b760bfa
Revises: 0d784c99194d
Create Date: 2026-08-02 03:32:36.552710

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '02913b760bfa'
down_revision = '0d784c99194d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS knowledge")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_documents_user_id'), 'documents', ['user_id'], unique=False, schema='knowledge')
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge.documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'chunks', ['document_id'], unique=False, schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='chunks', schema='knowledge')
    op.drop_table('chunks', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_documents_user_id'), table_name='documents', schema='knowledge')
    op.drop_table('documents', schema='knowledge')
    # ### end Alembic commands ###
