"""add memory schema, conversations and messages

Revision ID: 0d784c99194d
Revises: deac6ca389d1
Create Date: 2026-08-01 18:31:38.983140

"""
from alembic import op
import sqlalchemy as sa


revision = '0d784c99194d'
down_revision = 'deac6ca389d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS memory")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_index(op.f('ix_memory_conversations_user_id'), 'conversations', ['user_id'], unique=False, schema='memory')
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['memory.conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_index(op.f('ix_memory_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='memory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_messages_conversation_id'), table_name='messages', schema='memory')
    op.drop_table('messages', schema='memory')
    op.drop_index(op.f('ix_memory_conversations_user_id'), table_name='conversations', schema='memory')
    op.drop_table('conversations', schema='memory')
    # ### end Alembic commands ###
