"""add support schema, tickets and ticket_attachments

Revision ID: 308d99536b7b
Revises: b4f21e9c7a05
Create Date: 2026-08-12 17:59:47.510996

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '308d99536b7b'
down_revision = 'b4f21e9c7a05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS support")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='support'
    )
    op.create_index(op.f('ix_support_tickets_user_id'), 'tickets', ['user_id'], unique=False, schema='support')
    op.create_table('ticket_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('storage_ref', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support.tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='support'
    )
    op.create_index(op.f('ix_support_ticket_attachments_ticket_id'), 'ticket_attachments', ['ticket_id'], unique=False, schema='support')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_ticket_attachments_ticket_id'), table_name='ticket_attachments', schema='support')
    op.drop_table('ticket_attachments', schema='support')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='tickets', schema='support')
    op.drop_table('tickets', schema='support')
    # ### end Alembic commands ###


