"""add cloud_configs schema and cloud_configs table

Revision ID: 77926bc2b65d
Revises: ad7f0ec85b38
Create Date: 2026-08-03 15:18:05.756594

"""
from alembic import op
import sqlalchemy as sa


revision = '77926bc2b65d'
down_revision = 'ad7f0ec85b38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS cloud_configs")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('storage_ref', sa.String(length=500), nullable=False),
    sa.Column('resource_count', sa.Integer(), nullable=False),
    sa.Column('resource_types', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cloud_configs'
    )
    op.create_index(op.f('ix_cloud_configs_cloud_configs_user_id'), 'cloud_configs', ['user_id'], unique=False, schema='cloud_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_configs_cloud_configs_user_id'), table_name='cloud_configs', schema='cloud_configs')
    op.drop_table('cloud_configs', schema='cloud_configs')
    # ### end Alembic commands ###
