"""add job_drives schema and job_drives table

Revision ID: 7dce215c5ef5
Revises: aa816d50f07f
Create Date: 2026-08-05 19:04:46.366199

"""
from alembic import op
import sqlalchemy as sa


revision = '7dce215c5ef5'
down_revision = 'aa816d50f07f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS job_drives")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_drives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('experience_band', sa.String(length=20), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='job_drives'
    )
    op.create_index(op.f('ix_job_drives_job_drives_user_id'), 'job_drives', ['user_id'], unique=False, schema='job_drives')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_drives_job_drives_user_id'), table_name='job_drives', schema='job_drives')
    op.drop_table('job_drives', schema='job_drives')
    # ### end Alembic commands ###
