"""add mandatory profession field to users

Revision ID: aa816d50f07f
Revises: 77926bc2b65d
Create Date: 2026-08-05 16:55:24.244908

"""
from alembic import op
import sqlalchemy as sa


revision = 'aa816d50f07f'
down_revision = '77926bc2b65d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Bare NOT NULL with no default would fail against every pre-existing
    # user row (same gotcha as phase 9's role column) — backfill existing
    # rows to "it_professional" as a placeholder; every NEW registration
    # from here on always provides a real value explicitly (see
    # auth/schemas.py's UserCreate, which has no default and is mandatory).
    op.add_column(
        'users',
        sa.Column('profession', sa.String(length=20), nullable=False, server_default='it_professional'),
        schema='auth',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profession', schema='auth')
    # ### end Alembic commands ###
