"""add video schema and videos table

Revision ID: d3ae7eeeafc6
Revises: d9eed092f1f4
Create Date: 2026-08-02 09:32:41.306871

"""
from alembic import op
import sqlalchemy as sa


revision = 'd3ae7eeeafc6'
down_revision = 'd9eed092f1f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS video")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('storage_ref', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge.documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='video'
    )
    op.create_index(op.f('ix_video_videos_user_id'), 'videos', ['user_id'], unique=False, schema='video')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_videos_user_id'), table_name='videos', schema='video')
    op.drop_table('videos', schema='video')
    # ### end Alembic commands ###
