"""add orgs, invites, audit log, user roles

Revision ID: d9eed092f1f4
Revises: f114125a9c00
Create Date: 2026-08-02 08:50:05.321095

"""
from alembic import op
import sqlalchemy as sa


revision = 'd9eed092f1f4'
down_revision = 'f114125a9c00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS enterprise")

    op.create_table('orgs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )

    # Data backfill, not just a schema change: every existing user's org_id
    # is currently a random UUID with no orgs row behind it at all. Create
    # one org per distinct existing org_id BEFORE the FK constraint below is
    # added, or that constraint creation fails outright against real data.
    op.execute(
        "INSERT INTO auth.orgs (id, name, created_at) "
        "SELECT DISTINCT org_id, 'Personal', now() FROM auth.users"
    )

    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['auth.orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_index(op.f('ix_enterprise_audit_log_created_at'), 'audit_log', ['created_at'], unique=False, schema='enterprise')
    op.create_index(op.f('ix_enterprise_audit_log_org_id'), 'audit_log', ['org_id'], unique=False, schema='enterprise')
    op.create_table('invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['auth.orgs.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_index(op.f('ix_enterprise_invites_org_id'), 'invites', ['org_id'], unique=False, schema='enterprise')
    op.create_index(op.f('ix_enterprise_invites_token'), 'invites', ['token'], unique=True, schema='enterprise')

    # server_default so this doesn't fail against existing rows (autogenerate
    # produced a bare NOT NULL with no default, which errors on a non-empty
    # table) — every pre-existing user becomes "owner" of their own
    # single-person org, which is exactly correct: they were, structurally,
    # already the sole member of that org_id.
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='owner'), schema='auth')
    op.create_index(op.f('ix_auth_users_org_id'), 'users', ['org_id'], unique=False, schema='auth')
    op.create_foreign_key(None, 'users', 'orgs', ['org_id'], ['id'], source_schema='auth', referent_schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='auth', type_='foreignkey')
    op.drop_index(op.f('ix_auth_users_org_id'), table_name='users', schema='auth')
    op.drop_column('users', 'role', schema='auth')
    op.drop_index(op.f('ix_enterprise_invites_token'), table_name='invites', schema='enterprise')
    op.drop_index(op.f('ix_enterprise_invites_org_id'), table_name='invites', schema='enterprise')
    op.drop_table('invites', schema='enterprise')
    op.drop_index(op.f('ix_enterprise_audit_log_org_id'), table_name='audit_log', schema='enterprise')
    op.drop_index(op.f('ix_enterprise_audit_log_created_at'), table_name='audit_log', schema='enterprise')
    op.drop_table('audit_log', schema='enterprise')
    op.drop_table('orgs', schema='auth')
    # ### end Alembic commands ###
