"""add analytics schema and usage_events table

Revision ID: f114125a9c00
Revises: 02913b760bfa
Create Date: 2026-08-02 08:26:34.355555

"""
from alembic import op
import sqlalchemy as sa


revision = 'f114125a9c00'
down_revision = '02913b760bfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Alembic autogenerate never emits CREATE SCHEMA — same gotcha as every
    # previous new-schema migration in this project.
    op.execute("CREATE SCHEMA IF NOT EXISTS analytics")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('response_tokens', sa.Integer(), nullable=False),
    sa.Column('thoughts_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_usage_events_created_at'), 'usage_events', ['created_at'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_usage_events_user_id'), 'usage_events', ['user_id'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_usage_events_user_id'), table_name='usage_events', schema='analytics')
    op.drop_index(op.f('ix_analytics_usage_events_created_at'), table_name='usage_events', schema='analytics')
    op.drop_table('usage_events', schema='analytics')
    # ### end Alembic commands ###
